name: Análise de Segurança com Trivy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan-com-trivy:
    name: Scan com Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar scanner de vulnerabilidades Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          severity: "HIGH,CRITICAL"
          exit-code: "1"
